#pragma once

namespace GTS {

    //----------------------------------------
    // KEYBIND LIST
    //----------------------------------------

	static inline const std::vector<InputDef> DefaultBinds = {

		//----------------------------------
		// EXAMPLE
		//----------------------------------

		/*
		{
			 .Name = "Type.SubType.Action.SubAction", //The naming structure is purely for clarity. An eventname can be anything.
			 .Keys = { "F1", "F2", "F3" },            //List of keys to match against. Treated AND-wise, so all keys written must be pressed.
			 .UIName = "Name Shown In Settings Menu", //Visual name.
			 .UIDescription = "Description shown in settings when hovering over the keybind",
			 .Icon = "Icon Name Given To ImGraphics Driver",
			 .Trigger = BindTriggerType::Once,   //Keybind press behavior, Fire and forget, on (Delayed) release or Continious Hold Down.
			 .Block = BindBlockType::Automatic,  //When should vanilla input be blocked
			 .Group = BindGroup::kInterface,     //Input Category (Used for Settings UI).
			 .Duration = 1.0f,                   //Duration Key must be held down if Trigger type is Release.
			 .Exclusive = false,                 //If true the input event only fires if it's specific keys are the only ones being pressed.
			 .Advanced = false,                  //If true keybind is only visible and can fire if advanced settings are enabled.
		 },
		 */

		

		//----------------------------------
		// INTERFACE
		//----------------------------------

		{
			.Name = "UI.Settings.Open",
			.Keys = { "F1" },
			.UIName = "Settings Menu",
			.UIDescription = "Open this window, you can alternatively disable this keybind and use the \"gts menu\" console command to open the settings menu instead.",
			.Icon = "",
			.Block = BindBlockType::Always,
			.Group = BindGroup::kInterface,
	    },
	    {
	        .Name = "UI.SkillTree.Open",
	        .Keys = { "F4" },
	        .UIName = "Skill Tree",
	        .UIDescription = "Open the skill tree if \"Custom Skills Framework\" is Installed",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Block = BindBlockType::Always,
	        .Group = BindGroup::kInterface,
	    },
		{
			.Name = "UI.QuickStats.Show",
			.Keys = { "F3" },
			.UIName = "Quick Stats",
			.UIDescription = "Show brief size info for the player and current followers.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kInterface,
		},


		//----------------------------------
		// DEBUG
		//----------------------------------

	    {
	        .Name = "Debug.Menu.Open",
	        .Keys = { "LCONTROL", "LSHIFT", "F12" },
	        .UIName = "Debug Menu",
	        .UIDescription = "Open the debug menu.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Block = BindBlockType::Always,
	        .Group = BindGroup::kDebug,
	    	.Advanced = true,
	    },
	    {
	        .Name = "Debug.ActorInfo.Show",
	        .Keys = { "RCONTROL" },
	        .UIName = "Size Report",
	        .UIDescription = "Prints NPC/Player debug information in the console.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Group = BindGroup::kDebug,
	    	.Duration = 1.33f,
			.Advanced = true,
	    },


		//----------------------------------
		// ACTIONS / ANIMATIONS
		//----------------------------------


		// -------- SPECIAL UNIVERSAL KEYBINDS
		//This one is special. Its a modifier that if held down retargets actions to be used on the player through the nearest follower.
	    {
	        .Name = "Action.TargetPlayer",
	        .Keys = { "LALT" },
	        .UIName = "Target Self",
	        .UIDescription = "Hold while pressing an action key to have the nearest follower perform that action on you.",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Block = BindBlockType::Never,
	        .Group = BindGroup::kOther,
	    },
		//Holding down an action's key only speeds it up. If this is held down the action is slowed down instead.
		{
			.Name = "Action.SlowDown",
			.Keys = { "RMB" },
			.UIName = "Slow Down Action",
			.UIDescription = "Hold together with an action's own keys to slow that animation down instead of speeding it up.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kOther,
		},

		// -------- VORE
	    {
	        .Name = "Action.Vore.Start",
	        .Keys = { "LSHIFT", "V" },
	        .UIName = "Start Vore",
	        .UIDescription = "Start the basic vore action.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Group = BindGroup::kVore,
	    },

		// -------- THIGH CRUSH
		{
			.Name = "Action.ThighCrush.Start",
			.Keys = { "LSHIFT", "W", "C" },
			.UIName = "Start Thigh-Crush",
			.UIDescription = "Start the thigh crush action.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kThighCrush,
			.Exclusive = true,
		},
		{
			.Name = "Action.ThighCrush.Exit",
			.Keys = { "W" },
			.UIName = "Thigh-Crush Exit",
			.UIDescription = "Exit thigh crush mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kThighCrush,
			.Exclusive = true,
		},
		{
			.Name = "Action.ThighCrush.Attack",
			.Keys = { "LMB" },
			.UIName = "Thigh-Crush Attack",
			.UIDescription = "Perform a thigh crush attack / kill action.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kThighCrush,
		},

		// -------- THIGH SANDWICH [BASE]
	    {
	        .Name = "Action.ThighSandwich.Start",
	        .Keys = { "LSHIFT", "C" },
	        .UIName = "Start Thigh-Sandwich",
	        .UIDescription = "Start the thigh sandwich action.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Group = BindGroup::kThighSandwich,
	    	.Exclusive = true,
	    },
		{
			.Name = "Action.ThighSandwich.Exit",
			.Keys = { "W" },
			.UIName = "Thigh-Sandwich Exit",
			.UIDescription = "Exit thigh sandwich mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kThighSandwich,
			.Exclusive = true,
		},
		{
			.Name = "Action.ThighSandwich.AttackLight",
			.Keys = { "LMB" },
			.UIName = "Thigh-Sandwich L. Attack",
			.UIDescription = "Perform a light attack while in thigh sandwich mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Release,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kThighSandwich,
		},
		{
			.Name = "Action.ThighSandwich.AttackHeavy",
			.Keys = { "LMB" },
			.UIName = "Thigh-Sandwich H. Attack",
			.UIDescription = "Perform a heavy attack while in thigh sandwich mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kThighSandwich,
			.Duration = 0.33f,
		},


		// -------- THIGH SANDWICH [BUTT BRANCH]
		{
			.Name = "Action.ThighSandwich.ButtBranch.Enter",
			.Keys = { "LSHIFT", "H" },
			.UIName = "Thigh-Sandwich Butt Start",
			.UIDescription = "Enter thigh-sandwich butt mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kThighSandwich,
			.Exclusive = true,
		},
		{
			.Name = "Action.ThighSandwich.ButtBranch.Exit",
			.Keys = { "LSHIFT", "H" },
			.UIName = "Thigh-Sandwich Butt Stop",
			.UIDescription = "Exit thigh-sandwich butt mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kThighSandwich,
			.Exclusive = true,
		},
		{
			.Name = "Action.ThighSandwich.ButtBranch.GrindStart",
			.Keys = { "S" },
			.UIName = "Thigh-Sandwich Grind Start",
			.UIDescription = "Perform a continious grinding action on the NPC being butt-sandwiched.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kThighSandwich,
			.Exclusive = true,
		},
		{
			.Name = "Action.ThighSandwich.ButtBranch.GrindStop",
			.Keys = { "S" },
			.UIName = "Thigh-Sandwich Grind Stop",
			.UIDescription = "Stop grinding the butt-sandwichiched NPC.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kThighSandwich,
			.Exclusive = true,
		},
		{
			.Name = "Action.ThighSandwich.ButtBranch.Grow",
			.Keys = { "W" },
			.UIName = "Thigh-Sandwich Grow",
			.UIDescription = "Grow in size while in thigh-sandwich butt mode. Requires perk.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kThighSandwich,
			.Exclusive = true,
		},
		{
			.Name = "Action.ThighSandwich.ButtBranch.AttackHeavy",
			.Keys = { "LMB" },
			.UIName = "Thigh-Sandwich Butt Attack H.",
			.UIDescription = "Perform a heavy butt attack while in thigh-sandwich butt mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kThighSandwich,
			.Duration = 0.33f,
			.Exclusive = true,
		},
		{
			.Name = "Action.ThighSandwich.ButtBranch.AttackLight",
			.Keys = { "LMB" },
			.UIName = "Thigh-Sandwich Butt Attack L.",
			.UIDescription = "Perform a light butt attack while in thigh-sandwich butt mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Release,
			.Group = BindGroup::kThighSandwich,
			.Exclusive = true,
		},
		{
			.Name = "Action.ThighSandwich.ButtBranch.Unbirth",
			.Keys = { "V" },
			.UIName = "Thigh-Sandwich Unbirth/Vore",
			.UIDescription = "Vore the butt-sandwiched NPC.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kThighSandwich,
			.Duration = 0.33f,
			.Exclusive = true,
		},

		// -------- HUGS
		{
			.Name = "Action.Hugs.Start",
			.Keys = { "LSHIFT", "H" },
			.UIName = "Start Hug",
			.UIDescription = "Start a hug action and enter hug mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Release,
			.Group = BindGroup::kHugs,
		},
		{
			.Name = "Action.Hugs.Exit",
			.Keys = { "RMB" },
			.UIName = "Hug Exit / Release",
			.UIDescription = "Release the held NPC / target and exit hug mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kHugs,
			.Exclusive = true,
		},
		{
			.Name = "Action.Hugs.Shrink",
			.Keys = { "LMB" },
			.UIName = "Hug Shrink",
			.UIDescription = "Perform a hug shrink attack / action.",
			.Icon = "",
			.Trigger = BindTriggerType::Release,
			.Group = BindGroup::kHugs,
			.Exclusive = true,
		},
		{
			.Name = "Action.Hugs.Heal",
			.Keys = { "LMB" },
			.UIName = "Hug Heal",
			.UIDescription = "Perform a hug heal action.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Group = BindGroup::kHugs,
			.Duration = 0.33f,
			.Exclusive = true,
		},
		{
			.Name = "Action.Hugs.Crush",
			.Keys = { "S" },
			.UIName = "Hug Crush",
			.UIDescription = "Perfom a hug crush action (will kill the held target).",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kHugs,
		},

		// -------- STOMPS
		{
			.Name = "Action.Stomp.StartLight",
			.Keys = { "LSHIFT", "E" },
			.UIName = "Start L. Stomp",
			.UIDescription = "Start a light stomp action.",
			.Icon = "",
			.Trigger = BindTriggerType::Release,
			.Group = BindGroup::kStomps,
		},
		{
			.Name = "Action.Stomp.StartHeavy",
			.Keys = { "LSHIFT", "E" },
			.UIName = "Start H. Stomp",
			.UIDescription = "Start a heavy stomp action.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Group = BindGroup::kStomps,
			.Duration = 0.44f,
		},
		{
			.Name = "Action.Stomp.StartTrample",
			.Keys = { "LSHIFT", "E" },
			.UIName = "Start Trample",
			.UIDescription = "Start a trample action.",
			.Icon = "",
			.Trigger = BindTriggerType::Release,
			.Group = BindGroup::kStomps,
			.Duration = 0.20f,
		},

		// -------- KICKS
		{
			.Name = "Action.Kick.Light",
			.Keys = { "LALT", "E" },
			.UIName = "Start L. Kick",
			.UIDescription = "Perform a light kick.",
			.Icon = "",
			.Trigger = BindTriggerType::Release,
			.Group = BindGroup::kKickSwipe,
		},
		{
			.Name = "Action.Kick.HeavyHigh",
			.Keys = { "LALT", "E" },
			.UIName = "Start H. Kick",
			.UIDescription = "Perform a heavy kick.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Group = BindGroup::kKickSwipe,
			.Duration = 0.33f,
		},
		{
			.Name = "Action.Kick.HeavyLow",
			.Keys = { "LALT", "E" },
			.UIName = "Start H. Low Kick",
			.UIDescription = "Perform an alternative variant of the heavy kick.",
			.Icon = "",
			.Trigger = BindTriggerType::Release,
			.Group = BindGroup::kKickSwipe,
			.Duration = 0.1f,
		},

		// -------- SWIPES
		{
			.Name = "Action.Swipe.Heavy",
			.Keys = { "LALT", "E" },
			.UIName = "Start Swipe H.",
			.UIDescription = "Perform a light swipe attack (only works when sneaking / crawling).",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Group = BindGroup::kKickSwipe,
			.Duration = 0.33f,
		},
		{
			.Name = "Action.Swipe.Light",
			.Keys = { "LALT", "E" },
			.UIName = "Start Swipe L. ",
			.UIDescription = "Perform a light swipe attack (only works when sneaking / crawling).",
			.Icon = "",
			.Trigger = BindTriggerType::Release,
			.Group = BindGroup::kKickSwipe,
		},

		// -------- BUTT(& BREAST) CRUSH
		{
			.Name = "Action.Crush.StartQuick",
			.Keys = { "LSHIFT", "B" },
			.UIName = "Start Quick Crush",
			.UIDescription = "Start an untargeted butt / breast crush action.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Group = BindGroup::kCrush,
			.Duration = 1.0f,
		},
		{
			.Name = "Action.Crush.Start",
			.Keys = { "LSHIFT", "B" },
			.UIName = "Start Targeted Crush",
			.UIDescription = "Start a targeted butt / breast crush action and enter crush mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Release,
			.Group = BindGroup::kCrush,
		},
		{
			.Name = "Action.Crush.Attack",
			.Keys = { "LMB" },
			.UIName = "Crush Attack",
			.UIDescription = "Peform a crush attack, this will also exit crush mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kCrush,
		},
		{
			.Name = "Action.Crush.Grow",
			.Keys = { "W" },
			.UIName = "Crush Grow",
			.UIDescription = "Perform a grow action while in crush mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Group = BindGroup::kCrush,
		},

		// -------- GRABS [BASE]
		{
			.Name = "Action.Grab.Grab",
			.Keys = { "F" },
			.UIName = "Start Grab",
			.UIDescription = "Start a grab action and enter grab mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrab,
			.Duration = 0.25f,
		},
		{
			.Name = "Action.Grab.Release",
			.Keys = { "RMB" },
			.UIName = "Grab Exit / Release",
			.UIDescription = "Drop the held character and exit grab mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kGrab,
		},
		{
			.Name = "Action.Grab.Attack",
			.Keys = { "E" },
			.UIName = "Grab Attack",
			.UIDescription = "Perform a grab crush attack on a held character.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrab,
			.Duration = 0.50f,
		},
		{
			.Name = "Action.Grab.Throw",
			.Keys = { "X" },
			.UIName = "Grab Throw",
			.UIDescription = "Throw the held character and exit grab mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrab,
		},
		{
			.Name = "Action.Grab.Vore",
			.Keys = { "V" },
			.UIName = "Grab Vore",
			.UIDescription = "Vore the held character.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Group = BindGroup::kGrab,
			.Duration = 0.50f,
		},
		// -------- GRABS [GRAB PLAY]

		{
			.Name = "Action.Grab.GrabPlay.Enter",
			.Keys = { "LSHIFT", "H" },
			.UIName = "Start GrabPlay",
			.UIDescription = "Enter grab play mode with the held character.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrabPlay,
		},
		{
			.Name = "Action.Grab.GrabPlay.Exit",
			.Keys = { "LSHIFT", "H" },
			.UIName = "Exit GrabPlay",
			.UIDescription = "Exit grab play mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrabPlay,
		},
		{
			.Name = "Action.Grab.GrabPlay.Crush",
			.Keys = { "LMB" },
			.UIName = "GrabPlay Crush",
			.UIDescription = "Perform a crush attack.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrabPlay,
			.Duration = 0.5f,
		},
		{
			.Name = "Action.Grab.GrabPlay.Flick",
			.Keys = { "RMB" },
			.UIName = "GrabPlay Flick",
			.UIDescription = "Flick the held charcater away, this exits grab mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrabPlay,
		},
		{
			.Name = "Action.Grab.GrabPlay.GrindStart",
			.Keys = { "W" },
			.UIName = "GrabPlay Grind (Enter)",
			.UIDescription = "Enter the grabplay grind mode, this slowly damages the held character.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrabPlay,
		},
		{
			.Name = "Action.Grab.GrabPlay.GrindStop",
			.Keys = { "W" },
			.UIName = "GrabPlay Grind (Exit)",
			.UIDescription = "Exit grab play grind mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrabPlay,
		},
		{
			.Name = "Action.Grab.GrabPlay.Kiss",
			.Keys = { "E" },
			.UIName = "GrabPlay Kiss",
			.UIDescription = "Kiss the held character, healing them.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrabPlay,
		},
		{
			.Name = "Action.Grab.GrabPlay.KissVore",
			.Keys = { "V" },
			.UIName = "GrabPlay Vore During Kiss",
			.UIDescription = "Vore the held character whilst performing the kiss action.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrabPlay,
		},
		{
			.Name = "Action.Grab.GrabPlay.Vore",
			.Keys = { "V" },
			.UIName = "GrabPlay Vore",
			.UIDescription = "Vore the held character.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrabPlay,
		},
		{
			.Name = "Action.Grab.GrabPlay.Poke",
			.Keys = { "LMB" },
			.UIName = "GrabPlay Poke",
			.UIDescription = "Poke the held character.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrabPlay,
		},
		{
			.Name = "Action.Grab.GrabPlay.Sandwich",
			.Keys = { "S" },
			.UIName = "GrabPlay Sandwich",
			.UIDescription = "Perform a sandwich action.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kGrabPlay,
		},


		// -------- GRABS [BREAST PUT/TAKE]
		{
			.Name = "Action.Grab.Breasts.Place",
			.Keys = { "LSHIFT", "B" },
			.UIName = "Breasts Place",
			.UIDescription = "Place the held character between the holder's breasts.\n(This leaves grab mode, so you can grab another NPC while having another between breasts)",
			.Icon = "",
			.Group = BindGroup::kGrab,
			.Duration = 0.50f,
		},
		{
			.Name = "Action.Grab.Breasts.Remove",
			.Keys = { "LSHIFT", "B" },
			.UIName = "Breasts Remove",
			.UIDescription = "Remove the placed character from the holder's breasts.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kGrab,
			.Duration = 0.50f,
		},

		// -------- GRABS [CLEAVAGE MODE]
		{
			.Name = "Action.Cleavage.Enter",
			.Keys = { "LSHIFT", "H" },
			.UIName = "Start Cleavage Mode",
			.UIDescription = "Enter cleavage mode (Requires an NPC to be placed there first).",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kCleavage,
		},
		{
			.Name = "Action.Cleavage.Exit",
			.Keys = { "RMB" },
			.UIName = "Exit Cleavage Mode",
			.UIDescription = "Exit cleavage mode and return to breast hold mode.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kCleavage,
		},
		{
			.Name = "Action.Cleavage.AttackHeavy",
			.Keys = { "LMB" },
			.UIName = "Cleavage H. Attack",
			.UIDescription = "Perform a heavy attack.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kCleavage,
			.Duration = 0.33f,
			.Exclusive = true,
		},
		{
			.Name = "Action.Cleavage.AttackLight",
			.Keys = { "LMB" },
			.UIName = "Cleavage L. Attack",
			.UIDescription = "Perform a light attack.",
			.Icon = "",
			.Trigger = BindTriggerType::Release,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kCleavage,
			.Exclusive = true,
		},
		{
			.Name = "Action.Cleavage.Absorb",
			.Keys = { "S" },
			.UIName = "Cleavage Absorb",
			.UIDescription = "Absorb (and kill) the held NPC.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kCleavage,
		},
		{
			.Name = "Action.Cleavage.Strangle",
			.Keys = { "E" },
			.UIName = "Cleavage Strangle",
			.UIDescription = "Perform a cleavage strangle attack / action.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kCleavage,
		},
		{
			.Name = "Action.Cleavage.Suffocate",
			.Keys = { "W" },
			.UIName = "Cleavage Suffocate",
			.UIDescription = "Perform a cleavage suffocation attack / action.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kCleavage,
		},
		{
			.Name = "Action.Cleavage.Vore",
			.Keys = { "V" },
			.UIName = "Cleavage Vore",
			.UIDescription = "Vore/Eat the held NPC.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kCleavage,
		},

		//----------------------------------
		// MOVEMENT RELATED
		//----------------------------------

		// -------- CRAWLING TOGGLE
	    {
	        .Name = "Movement.Crawl.TogglePlayer",
	        .Keys = { "NUMPAD1" },
	        .UIName = "Toggle Crawl (Player)",
	        .UIDescription = "Swap between the regular sneak animations or an alternative crawl ones.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Group = BindGroup::kMovement,

	    },
	    {
	        .Name = "Movement.Crawl.ToggleFollower",
	        .Keys = { "NUMPAD3" },
	        .UIName = "Toggle Crawl (Followers)",
	        .UIDescription = "Swap between the regular sneak animations or an alternative crawl ones.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Group = BindGroup::kMovement,
	    },

		// -------- PRONING
		{
			.Name = "Movement.Prone.DiveSneak",
			.Keys = { "W", "S" },
			.UIName = "Prone Dive (Sneaking)",
			.UIDescription = "Enter prone mode by diving to the ground while sneaking / crawling.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kMovement,
			.Duration = 0.50f,
		},
		{
			.Name = "Movement.Prone.DiveStand",
			.Keys = { "W", "S" },
			.UIName = "Prone Dive (Standing)",
			.UIDescription = "Enter prone mode by diving to the ground while not sneaking / crawling.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,

			.Block = BindBlockType::Never,
			.Group = BindGroup::kMovement,
			.Duration = 0.50f,
		},
		{
			.Name = "Movement.Prone.Enter",
			.Keys = { "X" },
			.UIName = "Enter Prone",
			.UIDescription = "Enter Prone mode (only possible if already sneaking / crawling.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kMovement,
			.Duration = 0.66f,
		},

		//----------------------------------
		// ACTION ESCAPE / STRUGGLES
		//----------------------------------
		{
			.Name = "Struggle.Up",
			.Keys = { "W" },
			.UIName = "Struggle Up",
			.UIDescription = "Attempt to escape hugs or being grabbed",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kOther,
		},
		{
			.Name = "Struggle.Down",
			.Keys = { "S" },
			.UIName = "Struggle Down",
			.UIDescription = "Attempt to escape hugs or being grabbed",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kOther,
		},
		{
			.Name = "Struggle.Left",
			.Keys = { "A" },
			.UIName = "Struggle Left",
			.UIDescription = "Attempt to escape hugs or being grabbed",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kOther,
		},
		{
			.Name = "Struggle.Right",
			.Keys = { "D" },
			.UIName = "Struggle Right",
			.UIDescription = "Attempt to escape hugs or being grabbed",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Group = BindGroup::kOther,
		},

		//----------------------------------
		// CAMERA
		//----------------------------------
	    
	    {
	        .Name = "Camera.ResetHorizontal",
	        .Keys = { "RIGHT", "LEFT" },
	        .UIName = "Camera Reset (Horizontal)",
	        .UIDescription = "Reset the temporary horizontal camera offsets.",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Group = BindGroup::kCamera,
	    },
	    {
	        .Name = "Camera.ResetVertical",
	        .Keys = { "UP", "DOWN" },
	        .UIName = "Camera Reset (Vertical)",
	        .UIDescription = "Reset the temporary vertical camera offsets.",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Group = BindGroup::kCamera,
	    },
	    {
	        .Name = "Camera.MoveRight",
	        .Keys = { "LALT", "RIGHT" },
	        .UIName = "Shift Camera (Right)",
	        .UIDescription = "Temporarily shift the camera to the right.",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Group = BindGroup::kCamera,
	    },
	    {
	        .Name = "Camera.MoveLeft",
	        .Keys = { "LALT", "LEFT" },
	        .UIName = "Shift Camera (Left)",
	        .UIDescription = "Temporarily shift the camera to the left.",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Group = BindGroup::kCamera,
	    },
	    {
	        .Name = "Camera.MoveUp",
	        .Keys = { "LALT", "UP" },
	        .UIName = "Shift Camera (Up)",
	        .UIDescription = "Temporarily shift the camera upwards.",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Group = BindGroup::kCamera,
	    },
	    {
	        .Name = "Camera.MoveDown",
	        .Keys = { "LALT", "DOWN" },
	        .UIName = "Shift Camera (Down)",
	        .UIDescription = "Temporarily shift the camera downwards.",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Group = BindGroup::kCamera,
	    },
	    {
	        .Name = "Camera.SwitchMode",
	        .Keys = { "F2" },
	        .UIName = "Cycle Camera Mode",
	        .UIDescription = "Switch between alternative camera modes.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Group = BindGroup::kCamera,
	    },

		//----------------------------------
		// ABILITIES
		//----------------------------------
	    
		// -------- SHRINK OUTBURST
	    {
	        .Name = "Ability.ShrinkOutburst.Start",
	        .Keys = { "LSHIFT", "F" },
	        .UIName = "Shrink Outburst",
	        .UIDescription = "Do a shrink outburst attack, shrinking everyone near you.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Group = BindGroup::kAbilities,
	    },

		// -------- SIZE RESERVE
	    {
	        .Name = "Ability.SizeReserve.Grow",
	        .Keys = { "E" },
	        .UIName = "Size Reseve (Use)",
	        .UIDescription = "Apply the stored size reserve (the longer this is held down the more size is converted).",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Block = BindBlockType::Never,
	        .Group = BindGroup::kAbilities,
	    	.Duration = 1.33f,
	    },
		{
			.Name = "Ability.SizeReserve.ShowInfo",
			.Keys = { "F" },
			.UIName = "Size Reserve (Display)",
			.UIDescription = "Show a notification containing the amount of stored size reserve.",
			.Icon = "",
			.Trigger = BindTriggerType::Continuous,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kAbilities,
			.Duration = 1.33f,
		},

		// -------- PROTECT SMALL ONES
		{
			.Name = "Ability.ProtectSmallOnes.Start",
			.Keys = { "C" },
			.UIName = "Protect Small Ones",
			.UIDescription = "Activate the \"Protect Small Ones\" perk granting size damage immunity to others around you.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
			.Block = BindBlockType::Never,
			.Group = BindGroup::kAbilities,
			.Duration = 1.0f,
		},
	   
		// -------- SIZE ALTERATION [Manual]
	    {
	        .Name = "Ability.Size.GrowManual",
	        .Keys = { "UP", "LEFT" },
	        .UIName = "Grow (Manual)",
	        .UIDescription = "Slow continuous growth.",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Group = BindGroup::kAbilities,
	    },
	    {
	        .Name = "Ability.Size.ShrinkManual",
	        .Keys = { "DOWN", "LEFT" },
	        .UIName = "Shrink (Manual)",
	        .UIDescription = "Slow continuous shrinking.",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Group = BindGroup::kAbilities,
	    },
	    {
	        .Name = "Ability.Size.GrowManual.Other",
	        .Keys = { "LSHIFT", "UP", "LEFT" },
	        .UIName = "Grow Followers (Manual)",
	        .UIDescription = "Slow continuous growth.",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Group = BindGroup::kAbilities,
	    },
	    {
	        .Name = "Ability.Size.ShrinkManual.Other",
	        .Keys = { "LSHIFT", "DOWN", "LEFT" },
	        .UIName = "Shrink Folowers (Manual)",
	        .UIDescription = "Slow continuous shrinking.",
			.Icon = "",
	        .Trigger = BindTriggerType::Continuous,
	        .Group = BindGroup::kAbilities,
	    },


	    {
	        .Name = "Ability.Size.GrowManualOverTime",
	        .Keys = { "NUMPAD8" },
	        .UIName = "Grow (Incremental)",
	        .UIDescription = "An incremental non animated growth spurt.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Group = BindGroup::kAbilities,
	    },
	    {
	        .Name = "Ability.Size.ShrinkManualOverTime",
	        .Keys = { "NUMPAD4" },
	        .UIName = "Shrink (Incremental)",
	        .UIDescription = "An incremental non animated shrink spurt.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Group = BindGroup::kAbilities,
	    },
	    {
	        .Name = "Ability.Size.GrowManualOverTime.Other",
	        .Keys = { "NUMPAD5" },
	        .UIName = "Grow Folowers (Incremental)",
	        .UIDescription = "An incremental non animated growth spurt.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Group = BindGroup::kAbilities,
	    },
	    {
	        .Name = "Ability.Size.ShrinkManualOverTime.Other",
	        .Keys = { "NUMPAD2" },
	        .UIName = "Shrink Folowers (Incremental)",
	        .UIDescription = "An incremental non animated shrink spurt.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
	        .Group = BindGroup::kAbilities,
	    },

	    {
    		.Name = "Ability.Size.GrowBurst",
    		.Keys = { "LSHIFT", "1" },
    		.UIName = "Grow (Burst)",
    		.UIDescription = "A one-off animated growth spurt.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
    		.Group = BindGroup::kAbilities,
	    },
	    {
    		.Name = "Ability.Size.ShrinkBurst",
    		.Keys = { "LSHIFT", "2" },
    		.UIName = "Shrink (Burst)",
    		.UIDescription = "A one-off animated shrink spurt.",
			.Icon = "",
			.Trigger = BindTriggerType::Once,
    		.Group = BindGroup::kAbilities,
	    },

    };
}